# Holo 1.5-7B service extension for Bytebot Hawkeye
# Usage: docker compose -f docker-compose.yml -f docker-compose.holo.yml up -d

services:
  bytebot-holo:
    build:
      context: ../packages/bytebot-holo
      dockerfile: Dockerfile
    container_name: bytebot-holo
    restart: unless-stopped
    ports:
      - "9989:9989"
    environment:
      - HOLO_HOST=0.0.0.0
      - HOLO_PORT=9989
      - HOLO_DEVICE=${HOLO_DEVICE:-auto}  # auto, cuda, mps, or cpu
      - HOLO_MODEL_DTYPE=${HOLO_MODEL_DTYPE:-bfloat16}
      - HOLO_MAX_NEW_TOKENS=128
      - HOLO_CLICK_BOX_SIZE=40
      - HOLO_DEDUPLICATION_RADIUS=30
    volumes:
      # HuggingFace cache for Holo 1.5-7B model
      - holo_cache:/root/.cache/huggingface
    networks:
      - bytebot-network
    # GPU support: Automatically detected (no config needed for most users)
    # For explicit NVIDIA GPU reservation, add docker-compose.gpu.yml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9989/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 45s  # GPU loads model in 10-20s, 45s buffer for CPU fallback

  # Update bytebot-desktop to use Holo 1.5-7B
  bytebot-desktop:
    environment:
      - BYTEBOT_CV_USE_HOLO=${BYTEBOT_CV_USE_HOLO:-true}
      - HOLO_URL=${HOLO_URL:-http://bytebot-holo:9989}
      - HOLO_TIMEOUT=${HOLO_TIMEOUT:-120000}
    depends_on:
      bytebot-holo:
        condition: service_healthy

  # Update bytebot-agent to use Holo 1.5-7B
  bytebot-agent:
    environment:
      - BYTEBOT_CV_USE_HOLO=${BYTEBOT_CV_USE_HOLO:-true}
      - HOLO_URL=${HOLO_URL:-http://bytebot-holo:9989}
      - HOLO_TIMEOUT=${HOLO_TIMEOUT:-120000}
    depends_on:
      bytebot-holo:
        condition: service_healthy

volumes:
  holo_cache:
    driver: local
