model_list:
  - model_name: claude-opus-4
    litellm_params:
      model: anthropic/claude-opus-4-20250514
      api_key: os.environ/ANTHROPIC_API_KEY
    model_info:
      supports_vision: true
  - model_name: claude-sonnet-4
    litellm_params:
      model: anthropic/claude-sonnet-4-20250514
      api_key: os.environ/ANTHROPIC_API_KEY
    model_info:
      supports_vision: true
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: os.environ/OPENAI_API_KEY
    model_info:
      supports_vision: true
  - model_name: o3-pro
    litellm_params:
      model: openai/o3-pro
      api_key: os.environ/OPENAI_API_KEY
  - model_name: o3
    litellm_params:
      model: openai/o3
      api_key: os.environ/OPENAI_API_KEY
    model_info:
      supports_vision: false
  - model_name: o3-mini
    litellm_params:
      model: openai/o3-mini
      api_key: os.environ/OPENAI_API_KEY
    model_info:
      supports_vision: false
  - model_name: o1
    litellm_params:
      model: openai/o1
      api_key: os.environ/OPENAI_API_KEY
    model_info:
      supports_vision: false
  - model_name: o1-mini
    litellm_params:
      model: openai/o1-mini
      api_key: os.environ/OPENAI_API_KEY
    model_info:
      supports_vision: false
  - model_name: o1-preview
    litellm_params:
      model: openai/o1-preview
      api_key: os.environ/OPENAI_API_KEY
    model_info:
      supports_vision: false
  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY
    model_info:
      supports_vision: true
  - model_name: gpt-4.1
    litellm_params:
      model: openai/gpt-4.1
      api_key: os.environ/OPENAI_API_KEY
    model_info:
      supports_vision: true
  - model_name: gpt-5-thinking
    litellm_params:
      model: openai/gpt-5
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-5-main
    litellm_params:
      model: openai/gpt-5-chat-latest
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-5-mini
    litellm_params:
      model: openai/gpt-5-mini
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-5-nano
    litellm_params:
      model: openai/gpt-5-nano
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gemini-vertex-pro
    litellm_params:
      model: vertex_ai/gemini-1.5-pro
      vertex_project: gen-lang-client-0096858366
      vertex_location: us-central1
    model_info:
      supports_vision: true
  - model_name: gemini-vertex-flash
    litellm_params:
      model: vertex_ai/gemini-1.5-flash
      vertex_project: gen-lang-client-0096858366
      vertex_location: us-central1
    model_info:
      supports_vision: true
  - model_name: gemini-1.5-pro
    litellm_params:
      model: gemini/gemini-1.5-pro-latest
      api_key: os.environ/GEMINI_API_KEY
    model_info:
      supports_vision: true
  - model_name: gemini-1.5-flash
    litellm_params:
      model: gemini/gemini-1.5-flash-latest
      api_key: os.environ/GEMINI_API_KEY
    model_info:
      supports_vision: true
  - model_name: qwen3-vl-235b-a22b-instruct
    litellm_params:
      model: openrouter/qwen/qwen3-vl-235b-a22b-instruct
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      supports_vision: true
  - model_name: openrouter-claude-3.5-sonnet
    litellm_params:
      model: openrouter/anthropic/claude-3.5-sonnet
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      supports_vision: true
  - model_name: openrouter-claude-3.7-sonnet
    litellm_params:
      model: openrouter/anthropic/claude-3.7-sonnet
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      supports_vision: true
  - model_name: openrouter-gemini-2.5-flash
    litellm_params:
      model: openrouter/google/gemini-2.5-flash
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      supports_vision: true
  - model_name: openrouter-gemini-2.5-pro
    litellm_params:
      model: openrouter/google/gemini-2.5-pro
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      supports_vision: true
  - model_name: openrouter-glm-4.6
    litellm_params:
      model: openrouter/z-ai/glm-4.6
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      supports_vision: false
  - model_name: openrouter-deepseek-r1
    litellm_params:
      model: openrouter/deepseek/deepseek-r1
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      supports_vision: false
  - model_name: openrouter-deepseek-r1-distill-qwen-32b
    litellm_params:
      model: openrouter/deepseek/deepseek-r1-distill-qwen-32b
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      supports_vision: false
  - model_name: openrouter-deepseek-r1-distill-llama-70b
    litellm_params:
      model: openrouter/deepseek/deepseek-r1-distill-llama-70b
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      supports_vision: false
  - model_name: openrouter-qwen-plus
    litellm_params:
      model: openrouter/qwen/qwen-plus
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      supports_vision: false
  - model_name: openrouter-qwen-turbo
    litellm_params:
      model: openrouter/qwen/qwen-turbo
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      supports_vision: false
  - model_name: openrouter-qwen-max
    litellm_params:
      model: openrouter/qwen/qwen-max
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      supports_vision: false
  - model_name: openrouter-claude-3-haiku
    litellm_params:
      model: openrouter/anthropic/claude-3-haiku
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      supports_vision: false
  - model_name: openrouter-mistral-large
    litellm_params:
      model: openrouter/mistralai/mistral-large
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      supports_vision: false
  - model_name: openrouter-/internvl3-78b
    litellm_params:
      model: openrouter/opengvlab/internvl3-78b
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      supports_vision: true
  - model_name: openrouter-gemini-1.5-pro
    litellm_params:
      model: openrouter/google/gemini-1.5-pro-latest
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      supports_vision: true
  # Add local models via LMStudio
  - model_name: local-lmstudio-ui-tars-72b-dpo
    litellm_params:
      model: openai/ui-tars-72b-dpo
      api_base: http://192.168.4.250:1234/v1
      api_key: lm-studio
      supports_function_calling: true
  - model_name: local-lmstudio-gemma-3-27b
    litellm_params:
      model: openai/google/gemma-3-27b
      api_base: http://192.168.4.250:1234/v1
      api_key: lm-studio
      supports_function_calling: true
    model_info:
      supports_vision: true
  - model_name: local-lmstudio-qwen2.5-vl-32b-instruct
    litellm_params:
      model: openai/qwen2.5-vl-32b-instruct
      api_base: http://192.168.4.250:1234/v1
      api_key: lm-studio
      supports_function_calling: true
    model_info:
      supports_vision: true
  - model_name: local-lmstudio-ui-tars-7b-dpo
    litellm_params:
      model: openai/ui-tars-7b-dpo
      api_base: http://192.168.4.250:1234/v1
      api_key: lm-studio
      supports_function_calling: true
  - model_name: local-lmstudio-magistral-small-2509
    litellm_params:
      # Use OpenAI-compatible provider prefix for LM Studio
      model: openai/mistralai/magistral-small-2509
      api_base: http://192.168.4.250:1234/v1
      api_key: lm-studio
      supports_function_calling: true
    model_info:
      supports_vision: true

litellm_settings:
  drop_params: true
  set_verbose: false
